version: "2.1"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - TZ=America/Montreal
      - SUBDOMAINS=pics-cloud.duckdns.org
      - TOKEN=PAST-TOKEN
      - LOG_FILE=false #optional
    volumes:
      - /home/Henri/docker_file/duckdns/config:/config #optional
    restart: unless-stopped