version: "3.8"

networks:
  frontend_picsCloud:
    external: true
  backend_nextcloud:
    name: backend_nextcloud

services:

  nextcloud-app:
    container_name: nextcloud-app
    environment:
      - MYSQL_PASSWORD=mysqlpwd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - OVERWRITEPROTOCOL=https #pour permettre le bon fonctionnement du client Windows/Linux
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.pics-cloud.duckdns.org
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - /home/Henri/docker_file/nextcloud-app/var/www/html:/var/www/html
      - /home/Henri/photo:/photo
    networks:
      - frontend_picsCloud
      - backend_nextcloud
    depends_on:
      - nextcloud-db


  nextcloud-db:
    container_name: nextcloud-db
    environment:
      - MYSQL_ROOT_PASSWORD=5&HqHG4*zxT%*#P
      - MYSQL_PASSWORD=mysqlpwd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    restart: unless-stopped
    volumes:
      - /home/Henri/docker_file/nextcloud-db/var/lib/mysql:/var/lib/mysql
    networks:
      - backend_nextcloud


volumes:

  Photo:
    external: true