version: "2.1"

networks:
  nextcloud_frontend:
      external: true

services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - URL=pics-cloud.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=9251beb7-9d03-4f67-bf72-54c7d43ce19b
      - EMAIL= henri.delille.dh@gmail.com
    volumes:
      - /docker/swag/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - nextcloud_frontend    