version: "3.8"

networks:
  frontend:
  backend:

services:


  nextcloud-app:
    container_name: nextcloud-app
    environment:
      - MYSQL_PASSWORD=mysqlpwd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - OVERWRITEPROTOCOL=https #pour permettre le bon fonctionnement du client Windows/Linux
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.delisle.ovh
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - /docker-data/nextcloud-app/var/www/html:/var/www/html
      - /photo:/photo
    networks:
      - frontend
      - backend
    depends_on:
      - nextcloud-db

  nextcloud-db:
    container_name: nextcloud-db
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpwd
      - MYSQL_PASSWORD=mysqlpwd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    restart: unless-stopped
    volumes:
      - /home/henri/docker-data/nextcloud-db/var/lib/mysql:/var/lib/mysql
    networks:
      - backend
      
volumes:

  Photo:
    external: true